"""empty message

Revision ID: 2ff7854034f4
Revises: fa67a9f11fb3
Create Date: 2020-02-13 14:51:03.814410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff7854034f4'
down_revision = 'fa67a9f11fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('requests', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'service_id')
    op.drop_table('services')
    # ### end Alembic commands ###
