"""empty message

Revision ID: fa67a9f11fb3
Revises: 3cec80d5e55a
Create Date: 2020-02-13 14:06:04.542035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa67a9f11fb3'
down_revision = '3cec80d5e55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('requests', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'status_id')
    op.drop_table('statuses')
    # ### end Alembic commands ###
